### ISSUE TITLE
[meta] Support the drawing with Gfx_rs

### ISSUE THREAD

**Issue by loki04** [szeged/webrender#1]
The main goal is to adopt Gfx_rs in WebRender which can be used to draw on the screen with different gfx driver.

**Comment by dati91** [comment]
The Gfx-rs repository - https://github.com/gfx-rs/gfx
Introduction - https://wiki.alopex.li/LearningGfx

**Comment by dati91** [comment]
Task list:
- [ ] Investigate WebGL #3 
- [ ] Create pipeline for `ps_rectangle` #8 
- [ ] Encapsulate Shaders (pso,data,slice)
- [ ] Handle varying texture/sampler size
- [ ] Replace the min_ps_rectangle with the original ps_rectangle shader (extend with the "unused" attributes)
- [ ] Add transform and clip variant for ps_rectangle
- [ ] Add another shaders
- [ ] Implement Textures (for ps_image) #6
