### ISSUE TITLE
[meta] Performance opportunities on the horison

### ISSUE THREAD

**Issue by kvark** [szeged/webrender#212]
Merely porting the existing WR device to gfx-hal is just a start. The real fruits will come once we make deeper changes to the WR architecture to take the benefit of modern graphics APIs. This meta-issue is tracking those architectural changes:
- [ ] Parallel recording -  #188
- [ ] Specialization - #211
- [ ] In-place instance data - #219
- [ ] Share descriptor sets between instances and frames - https://github.com/szeged/webrender/issues/236
- [ ] Pipeline cache - #241 
- [ ] Better memory management - #255

**Comment by dati91** [comment]
- [ ] Share descriptor sets between instances and frames - https://github.com/szeged/webrender/issues/236

**Comment by zakorgy** [comment]
- [ ] Better memory management - #255
