### ISSUE TITLE
Check the validation layer

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#80]
Now that most of the major components are in place, we should pay more attention to the validation layer.

We can collect the issues here and identify the corresponding code, then fix it.

**Comment by dati91** [comment]
The following errors are from [this](c4d1f532d8fb1f8b9ebcbaa00c9d611f524ce09e) revision.
I ran the `basic` and `blob` examples and picked the common errors for starter.

- [ ] ERROR:<unknown>: [ParameterValidation] vkCreateSampler(): The samplerAnisotropy feature was not enabled at device-creation time, so the maxAnisotropy member of the VkSamplerCreateInfo structure must be 1.0 but is 0.000000.
- [ ] ERROR:<unknown>: [DS] vkCreateFramebuffer(): VkFramebufferCreateInfo attachment #0 has format of VK_FORMAT_R8_UNORM that does not match the format of VK_FORMAT_B8G8R8A8_UNORM used by the corresponding attachment for renderPass (0x6). The spec valid usage text states 'Each element of pAttachments must have been created with an VkFormat value that matches the VkFormat specified by the corresponding VkAttachmentDescription in renderPass' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkFramebufferCreateInfo-pAttachments-00880)
- [ ] ERROR:<unknown>: [DS] vkCmdPipelineBarrier(): pImageMemBarriers[0].dstAccessMask (See below) is not supported by dstStageMask (0x2000). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)
  - With two different `dstAccessMask`: `0x180` and `0x600`
- [ ] ERROR:<unknown>: [DS] vkCmdPipelineBarrier(): pImageMemBarriers[0].srcAccessMask (0x20) is not supported by srcStageMask (0x1). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its srcAccessMask member if that bit is not supported by any of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)
- [ ] ERROR:<unknown>: [IMAGE] vkCmdCopyBufferToImage(): pRegion[0] exceeds image bounds. The spec valid usage text states 'The image region specified by each element of pRegions must be a region that is contained within dstImage' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdCopyBufferToImage-pRegions-00172).

There are other errors, but we can start with these first.

**Comment by kvark** [comment]
- `vkCreateSampler()` already addressed in https://github.com/gfx-rs/gfx/commit/e30271227df027b7b8e2d239bd7ec39d5e4146e6
- another error not listed here is addressed in https://github.com/gfx-rs/gfx/commit/e3a6515e652732e6095c91cc0dfbfa094a9c89ac

**Comment by dati91** [comment]
More errors:

From basic:

- [ ] ERROR:<unknown>: [DS] You cannot start a render pass using a framebuffer with a different number of attachments.
ERROR:<unknown>: [DS] vkCmdBeginRenderPass(): RenderPasses incompatible between render pass w/ renderPass 0x6 and framebuffer w/ renderPass 0x7 Attachment 4294967295 is not compatible with 1: The first is unused while the second is not.. The spec valid usage text states 'renderPass must be compatible with the renderPass member of the VkFramebufferCreateInfo structure specified when creating framebuffer.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkRenderPassBeginInfo-renderPass-00904)
ERROR:<unknown>: [DS] Descriptor set 0x39 encountered the following validation error at vkCmdDraw() time: Descriptor in binding #13 at global descriptor index 13 is being used in draw but has not been updated.
  - Issue: N/A

From blob:

- [ ] ERROR:<unknown>: [DS] Descriptor set 0x4e encountered the following validation error at vkCmdDraw() time: Descriptor in binding #1 at global descriptor index 1 requires an image view of type VK_IMAGE_VIEW_TYPE_2D_ARRAY but got VK_IMAGE_VIEW_TYPE_2D.
  - Issue: N/A
- [ ] ERROR:<unknown>: [DS] Cannot submit cmd buffer using image (0x4) [sub-resource: aspectMask 0x1 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR when first use is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL.
  - Issue: N/A

**Comment by dati91** [comment]
> vkCreateSampler() already addressed in gfx-rs/gfx@e302712

The issue

> ERROR:: [ParameterValidation] vkCreateSampler(): The samplerAnisotropy feature was not enabled at device-creation time, so the maxAnisotropy member of the VkSamplerCreateInfo structure must be 1.0 but is 0.000000.

is still exist because the default value [here](https://github.com/gfx-rs/gfx/commit/e30271227df027b7b8e2d239bd7ec39d5e4146e6#diff-055df6f698963e935780372c2266b221R781) is set to `0.0` instead of `1.0` as the error states.

cc @kvark

**Comment by kvark** [comment]
argh, sorry

**Comment by zakorgy** [comment]
Another error:
- [ ] ERROR:<unknown>: [DS] vkCreateSwapChainKHR() called with minImageCount = 2, which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR() (i.e. minImageCount = 4, maxImageCount = 0). The spec valid usage text states 'minImageCount must be greater than or equal to the value returned in the minImageCount member of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-minImageCount-01271)

**Comment by dati91** [comment]
The remaining errors from reftest

- [ ] ERROR:: [DS] Descriptor set 0x131a encountered the following validation error at vkCmdDraw() time: Descriptor in binding #1 at global descriptor index 1 is being used in draw but has not been updated.
- [ ] ERROR:: [DS] vkCmdPipelineBarrier(): Image barrier 0x0x7ffdabcdfed0 newLayout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL is not compatible with image 0x11c usage flags 0x16. The spec valid usage text states 'If either oldLayout or newLayout is VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL then image must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT set' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01212)
- [ ] ERROR:: [DS] vkCmdPipelineBarrier(): pImageMemBarriers[0].dstAccessMask (0x180) is not supported by dstStageMask (0x1000). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)
- [ ] ERROR:: [DS] vkCmdPipelineBarrier(): pImageMemBarriers[0].srcAccessMask (0x1000) is not supported by srcStageMask (0x1). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its srcAccessMask member if that bit is not supported by any of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)
- [ ] ERROR:: [DS] You are adding vkQueueSubmit() to command buffer 0x7f2ebe00da00 that is invalid because bound DescriptorSet 0x501 was destroyed or updated.
- [ ] ERROR:: [MEM] Invalid usage flag for Image 0x11c used by vkCmdCopyImage(). In this case, Image should have VK_IMAGE_USAGE_TRANSFER_SRC_BIT set during creation. The spec valid usage text states 'srcImage must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT usage flag' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdCopyImage-srcImage-00126)
- [ ] ERROR:: [MEM] Invalid usage flag for Image 0x1943 used by vkCmdBlitImage(). In this case, Image should have VK_IMAGE_USAGE_TRANSFER_SRC_BIT set during creation. The spec valid usage text states 'srcImage must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT usage flag' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdBlitImage-srcImage-00219)
- [ ] ERROR:: [MEM] Invalid usage flag for Image 0x4 used by vkCmdCopyImageToBuffer(). In this case, Image should have VK_IMAGE_USAGE_TRANSFER_SRC_BIT set during creation. The spec valid usage text states 'srcImage must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT usage flag' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdCopyImageToBuffer-srcImage-00186)
- [ ] ERROR:: [ObjectTracker] OBJ ERROR : For device 0x7f2ec27b5000, DeviceMemory object 0x9 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
    - Also for others: 3 x `Framebuffer`, `Image`, 2 x `ImageView`, 2 x `Sampler`, `SwapchainKHR`
- [ ] ERROR:: [ObjectTracker] Unable to remove Image obj 0x4. Was it created? Has it already been destroyed?
- [ ] ERROR:: [SC] Vertex shader consumes input at location 4 but not provided

**Comment by dati91** [comment]
The remaining issues:

- [ ] ERROR:: [DS] Object: 0x105a | Descriptor set 0x105a encountered the following validation error at vkCmdDraw() time: Descriptor in binding #1 at global descriptor index 1 is being used in draw but has not been updated.
- [ ] ERROR:: [DS] Object: 0x7f2b421a6400 | You are adding vkQueueSubmit() to command buffer 0x7f2b421a6400 that is invalid because bound DescriptorSet 0x1602 was destroyed or updated.
- [ ] ERROR:: [DS] Object: 0x7f2b421a6e00 | vkCmdSetBlendConstants(): pipeline was created without VK_DYNAMIC_STATE_BLEND_CONSTANTS flag. The spec valid usage text states 'The currently bound graphics pipeline must have been created with the VK_DYNAMIC_STATE_BLEND_CONSTANTS dynamic state enabled' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdSetBlendConstants-None-00612).
- [ ] ERROR:: [DS] Object: 0x8 | vkCmdDraw(): RenderPasses incompatible between active render pass w/ renderPass 0x8 and pipeline state object w/ renderPass 0x6 Attachment 0 is not compatible with 0: They have different formats.. The spec valid usage text states 'The current render pass must be compatible with the renderPass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline currently bound to VK_PIPELINE_BIND_POINT_GRAPHICS.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdDraw-renderPass-00435)

We need to fix the barriers #99 
- [ ] ERROR:: [DS] Object: 0x7f2b421a6e00 | vkCmdPipelineBarrier(): pImageMemBarriers[0].srcAccessMask (0x800) is not supported by srcStageMask (0x1). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its srcAccessMask member if that bit is not supported by any of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)
- [ ] ERROR:: [DS] Object: 0x7f2b46618000 | vkCmdPipelineBarrier(): pImageMemBarriers[0].dstAccessMask (0x180) is not supported by dstStageMask (0x2000). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)
- [ ] ERROR:: [DS] Object: 0x7f2b46618000 | vkCmdPipelineBarrier(): pImageMemBarriers[1].dstAccessMask (0x180) is not supported by dstStageMask (0x2000). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)
- [ ] ERROR:: [DS] Object: 0x7f2b46618000 | vkCmdPipelineBarrier(): pImageMemBarriers[1].srcAccessMask (0x180) is not supported by srcStageMask (0x1). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its srcAccessMask member if that bit is not supported by any of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)

The cache clip shaders don't use the aData input attributes.
- [ ] ERROR:: [SC] Object: 0x0 | Vertex shader consumes input at location 4 but not provided
- [ ] ERROR:: [SC] Object: 0x0 | Vertex shader consumes input at location 5 but not provided

We are not releasing the resources correctly
- [ ] ERROR:: [ObjectTracker] Object: 0x10a1 | OBJ ERROR : For device 0x7f2b46e58800, DescriptorSetLayout object 0x10a1 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0x10a2 | OBJ ERROR : For device 0x7f2b46e58800, DescriptorPool object 0x10a2 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0x10a3 | OBJ ERROR : For device 0x7f2b46e58800, DescriptorSet object 0x10a3 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0x10a4 | OBJ ERROR : For device 0x7f2b46e58800, PipelineLayout object 0x10a4 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0x10a5 | OBJ ERROR : For device 0x7f2b46e58800, Pipeline object 0x10a5 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0x10b1 | OBJ ERROR : For device 0x7f2b46e58800, Buffer object 0x10b1 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0x10b2 | OBJ ERROR : For device 0x7f2b46e58800, DeviceMemory object 0x10b2 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0x13 | OBJ ERROR : For device 0x7f2b46e58800, Sampler object 0x13 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0x3 | OBJ ERROR : For device 0x7f2b46e58800, SwapchainKHR object 0x3 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0x4 | Unable to remove Image obj 0x4. Was it created? Has it already been destroyed?
- [ ] ERROR:: [ObjectTracker] Object: 0xa | OBJ ERROR : For device 0x7f2b46e58800, Image object 0xa has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
- [ ] ERROR:: [ObjectTracker] Object: 0xc | OBJ ERROR : For device 0x7f2b46e58800, ImageView object 0xc has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)

**Comment by dati91** [comment]
- [ ] ERROR:: [DS] Object: 0x163b | CmdBindPipeline: vkPipeline (0x163b) attachment[0] has a dual-source blend factor but this device feature is not enabled.

**Comment by dati91** [comment]
It seems like I missed something in the latest rebase.
It most probably related to the new `DashAndDot` Vertex array kind.
- [ ] ERROR [SC] Object: 0x0 | fragment shader consumes input location 6.0 which is not written by vertex shader
- [ ] ERROR [SC] Object: 0x0 | fragment shader consumes input location 7.0 which is not written by vertex shader
- [ ] ERROR [DS] Object: 0x6 | vkCmdDraw(): RenderPasses incompatible between active render pass w/ renderPass 0x6 and pipeline state object w/ renderPass 0x8 Attachment 0 is not compatible with 0: They have different formats.. The spec valid usage text states 'The current render pass must be compatible with the renderPass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline currently bound to VK_PIPELINE_BIND_POINT_GRAPHICS.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdDraw-renderPass-00435)

**Comment by dati91** [comment]
- [ ] ERROR gfx_backend_vulkan: [Validation]  [ VUID-VkMappedMemoryRange-offset-00687 ] Object: 0xaf (Type = 8) | vkFlushMappedMemoryRanges: Offset in pMemRanges[0] is 0x260, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). The spec valid usage text states 'offset must be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkMappedMemoryRange-offset-00687)
  - This one occurs when we use a mapping writer for the instance buffer. We allocate a large buffer and only write into a smaller chunk. And the offset + size is not a multiple of `nonCoherentAtomSize` (64).

**Comment by zakorgy** [comment]
After updating the VulkanSDK we have new validation layer error(s), which we should take care:

Descriptor set related:
- [ ] VALIDATION [UNASSIGNED-CoreValidation-DrawState-InvalidCommandBuffer (0)] : You are adding vkQueueSubmit() to command buffer 0x55932df42c80 that is invalid because bound DescriptorSet 0x47 was destroyed or updated.
object info: (type: COMMAND_BUFFER, hndl: 94090619530368)

- [ ] VALIDATION [VUID-VkWriteDescriptorSet-descriptorType-01403 (0)] : vkUpdateDescriptorSets() failed write update validation for Descriptor Set 0x2d with error: Write update to VkDescriptorSet 0x2d allocated with VkDescriptorSetLayout 0x2c binding #2 failed with error message: Attempted write update to image descriptor failed due to: Descriptor update with descriptorType VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE is being updated with invalid imageLayout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. Allowed layouts are: VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_GENERAL. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE or VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, the imageLayout member of each element of pImageInfo must be a member of the list given in Sampled Image or Combined Image Sampler, corresponding to its type (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-01403)
object info: (type: DESCRIPTOR_SET, hndl: 45)


These are happening after window resize:
- [ ] ERROR 2019-05-02T11:30:08Z: gfx_backend_vulkan: 
VALIDATION [UNASSIGNED-CoreValidation-DrawState-InvalidRenderArea (0)] : Cannot execute a render pass with renderArea not within the bound of the framebuffer. RenderArea: x 0, y 0, width 1920, height 1107. Framebuffer: width 1440, height 1080.
object info: (type: UNKNOWN, hndl: 0)

- [ ] ERROR 2019-05-02T11:30:08Z: gfx_backend_vulkan: 
VALIDATION [VUID-VkImageBlit-dstOffset-00248 (0)] : vkCmdBlitImage: region [0] dstOffset[].x values (1392, 1904) exceed dstSubresource width extent (1440). The Vulkan spec states: dstOffset[0].x and dstOffset[1].x must both be greater than or equal to 0 and less than or equal to the destination image subresource width (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageBlit-dstOffset-00248)
object info: (type: COMMAND_BUFFER, hndl: 94821767681360)
------------------------------------------------------
And there is a D3D12 error:
- [ ] D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Using ResourceBarrier on Command List (0x403890B8:'Unnamed ID3D12GraphicsCommandList Object'): Before state (0x4: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x181BDB60:'Unnamed ID3D12Resource Object') (subresource: 0) specified by transition barrier does not match with the state (0x0: D3D12_RESOURCESTATE[COMMON|PRESENT]) specified in the previous call to ResourceBarrier [ RESOURCE_MANIPULATION ERROR # 527: RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH]

**Comment by zakorgy** [comment]
We encountered the following issue with an Nvidia card:
- [ ] VUID-VkBufferImageCopy-bufferOffset-00193(ERROR / SPEC): msgNum: 0 - vkCmdCopyBufferToImage(): pRegion[0] bufferOffset 0x13f28 must be a multiple of this format's texel size (16). The Vulkan spec states: If the calling command's VkImage parameter's format is not a depth/stencil format, then bufferOffset must be a multiple of the format's texel block size. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkBufferImageCopy-bufferOffset-00193)
    Objects: 1
        [0] 0x65, type: 10, name: NULL

**Comment by zakorgy** [comment]
These are Gecko related:
- [ ] UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass(ERROR / SPEC): msgNum: 0 - You cannot start a render pass using a framebuffer with a different number of attachments.
    Objects: 1
        [0] 0xec4ca40, type: 6, name: NULL
- [ ] VUID-VkRenderPassBeginInfo-renderPass-00904(ERROR / SPEC): msgNum: 0 - vkCmdBeginRenderPass(): RenderPasses incompatible between render pass w/ renderPass 0x7 and framebuffer w/ renderPass 0x8 Attachment 4294967295 is not compatible with 1: The first is unused while the second is not.. The Vulkan spec states: renderPass must be compatible with the renderPass member of the VkFramebufferCreateInfo structure specified when creating framebuffer. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkRenderPassBeginInfo-renderPass-00904)
    Objects: 1
        [0] 0x7, type: 18, name: NULL
